name: dev-build-deploy

on:
  pull_request:
    branches: [ dev ]

jobs:
  dev-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python & Cache Dependencies
        uses: actions/setup-python@v3
        with:
          python-version: "3"
          cache: 'pip'
      - name: Install Requirements 
        run: make requirements
      - name: Lint
        run: make lint
      - name: Build
        run: make build

  dev-deploy:
    runs-on: ubuntu-latest
    needs: [dev-build]
    environment: development
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python & Cache Dependencies
        uses: actions/setup-python@v3
        with:
          python-version: '3'
          cache: 'pip'
      - name: build-again
        run: make build
